# Generated by Django 4.1.2 on 2022-10-13 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='dt_criacao',
        ),
    ]
