# Generated by Django 4.1.2 on 2022-10-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='descricao',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
