# Generated by Django 4.1.2 on 2022-10-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_documents_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name_plural': 'Documents'},
        ),
    ]
