# Generated by Django 4.1.2 on 2022-10-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_alter_documents_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
